<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE action-mappings [
	<!ELEMENT action-mappings (action*)>
	<!ELEMENT action (forward*)>
	<!ELEMENT forward EMPTY>
	<!ATTLIST action path CDATA #REQUIRED>
	<!ATTLIST action type CDATA #REQUIRED>
	<!ATTLIST action parameter CDATA #REQUIRED>
	<!ATTLIST forward name CDATA #REQUIRED>
	<!ATTLIST forward path CDATA #REQUIRED>
	<!ATTLIST forward redirect CDATA "false">
]>
<action-mappings>
	<!-- 注册 -->
	<action path="/regist" type="com.itany.bbs.action.UserAction" parameter="regist">
		<forward name="success" path="/pages/success.jsp" redirect="false"></forward>
		<forward name="fail" path="/pages/regist.jsp"></forward>
	</action>
	<!-- 登录 -->
	<action path="/login" type="com.itany.bbs.action.UserAction" parameter="login">
		<forward name="success" path="/index.do" redirect="true"></forward>
		<forward name="fail" path="/pages/login.jsp"></forward>
	</action>
	<!-- 退出注销 -->
	<action path="/exit" type="com.itany.bbs.action.UserAction" parameter="exit">
		<forward name="success" path="/pages/login.jsp" redirect="true"></forward>
		<forward name="fail" path="/pages/findpwd.jsp"></forward>
	</action>
	
	<action path="/email" type="com.itany.bbs.action.UserAction" parameter="email">
		<forward name="success" path="/index.do" redirect="true"></forward>
		<forward name="fail" path="/pages/login.jsp"></forward>
	</action>
	
	<!-- 首页获取板块信息 -->
	<action path="/index" type="com.itany.bbs.action.BoardAction" parameter="findAllBoard">
		<forward name="success" path="/pages/index.jsp" redirect="true"></forward>
	</action>
	
	<!-- 论坛主题帖相关信息 -->
	<action path="/topic" type="com.itany.bbs.action.TopicAction" parameter="findAllTopic">
		<forward name="success" path="/pages/topic.jsp" redirect="false"></forward>
		<forward name="login" path="/pages/err.jsp"  redirect="false"></forward>
		<forward name="fail" path="/pages/login.jsp"></forward>
	</action>
	
	<!-- 论坛置顶帖相关信息 -->
	<action path="/top" type="com.itany.bbs.action.TopicAction" parameter="findTopTopic">
		<forward name="success" path="/pages/Top.jsp" redirect="false"></forward>
		<forward name="login" path="/pages/err.jsp"  redirect="false"></forward>
		<forward name="fail" path="/pages/login.jsp"></forward>
	</action> 
	<!-- 论坛精华帖相关信息 -->
	<action path="/good" type="com.itany.bbs.action.TopicAction" parameter="findGoodTopic">
		<forward name="success" path="/pages/Good.jsp" redirect="false"></forward>
		<forward name="fail" path="/pages/login.jsp"></forward>
	</action> 
	<!-- 论坛发帖相关信息 -->
	<action path="/publish" type="com.itany.bbs.action.TopicAction" parameter="publish">
		<forward name="success" path="/topic.do" redirect="false"></forward>
		<forward name="err" path="/pages/err.jsp"  redirect="false"></forward>
		<forward name="fail" path="/pages/publish.jsp"></forward>
	</action>
	<!-- 论坛设置置顶帖子 -->
	<action path="/totop" type="com.itany.bbs.action.TopicAction" parameter="totop">
		<forward name="success" path="/top.do"  ></forward>
		<forward name="fail" path="/pages/404.html"></forward>
	</action>
	<!-- 论坛设置精华帖子 -->
	<action path="/togood" type="com.itany.bbs.action.TopicAction" parameter="togood">
		<forward name="success" path="/good.do"  ></forward>
		<forward name="fail" path="/pages/404.html"></forward>
	</action>
	
	<!-- 所有发帖 -->
	<action path="/finallsend" type="com.itany.bbs.action.TopicAction" parameter="findAll">
		<forward name="success" path="/adpages/showall.jsp"  ></forward>
		<forward name="fail" path="/pages/404.html"></forward>
	</action>
	
	<!-- 根据boardname发帖 -->
	<action path="/sendBybdname" type="com.itany.bbs.action.TopicAction" parameter="findTopicByBname">
		<forward name="success" path="/adpages/showall.jsp"  ></forward>
		<forward name="fail" path="/pages/404.html"></forward>
	</action>
	
	<!-- 后台修帖子信息 -->
	<action path="/xiugai" type="com.itany.bbs.action.TopicAction" parameter="xiugaiopic">
		<forward name="success" path="/adpages/showall.jsp" redirect="false"></forward>
		<forward name="fail" path="/pages/login.jsp"></forward>
	</action>
	<!-- 后台删除帖子信息 -->
	<action path="/deletetopic" type="com.itany.bbs.action.TopicAction" parameter="delet">
		<forward name="success" path="/adpages/showall.jsp" redirect="false"></forward>
		<forward name="fail" path="/pages/login.jsp"></forward>
	</action>
	<!-- 根据boardname回帖 -->
	<action path="/getBybdname" type="com.itany.bbs.action.ReplyAction" parameter="findreplysByBname">
		<forward name="success" path="/adpages/showallht.jsp"  ></forward>
		<forward name="fail" path="/pages/404.html"></forward>
	</action>
	<!-- 所有回帖 -->
	<action path="/findallget" type="com.itany.bbs.action.ReplyAction" parameter="findAll">
		<forward name="success" path="/adpages/showallht.jsp"></forward>
		<forward name="fail" path="/pages/404.html"></forward>
	</action>
	
	<!-- 论坛回复相关信息 -->
	<action path="/replay" type="com.itany.bbs.action.ReplyAction" parameter="findAllReplay">
		<forward name="success" path="/pages/replay.jsp" redirect="false"></forward>
		<forward name="err" path="/pages/err.jsp"  redirect="false"></forward>
		<forward name="fail" path="/pages/login.jsp"></forward>
	</action>
	
	
	<!-- 回复论坛发帖相关信息 -->
	<action path="/remodify" type="com.itany.bbs.action.ReplyAction" parameter="remodify">
		<forward name="success" path="/pages/modify.jsp" redirect="false"></forward>
		<forward name="err" path="/pages/err.jsp"  redirect="false"></forward>
		<forward name="fail" path="/pages/login.jsp"></forward>
	</action>
	
	
	<!-- 论坛发布回复帖子信息 -->
	<action path="/post" type="com.itany.bbs.action.ReplyAction" parameter="post">
		<forward name="success" path="/replay.do" redirect="false"></forward>
		<forward name="err" path="/pages/err.jsp"  redirect="false"></forward>
		<forward name="index" path="/pages/index.jsp"></forward>
		<forward name="fail" path="/pages/login.jsp"></forward>
	</action>
	
	<!-- 论坛删除回复帖子信息 -->
	<action path="/delete" type="com.itany.bbs.action.ReplyAction" parameter="delete">
		<forward name="success" path="/replay.do" redirect="false"></forward>
		<forward name="err" path="/pages/err.jsp"  redirect="false"></forward>
		<forward name="index" path="/pages/index.jsp"></forward>
		<forward name="fail" path="/pages/login.jsp"></forward>
	</action>
	
	<!-- 论坛修改发布帖子信息 -->
	<action path="/modify" type="com.itany.bbs.action.ReplyAction" parameter="modify">
		<forward name="success" path="/replay.do" redirect="false"></forward>
		<forward name="err" path="/pages/err.jsp"  redirect="false"></forward>
		<forward name="index" path="/pages/index.jsp"></forward>
		<forward name="fail" path="/pages/login.jsp"></forward>
	</action>
	<!-- 后台修改发布帖子信息 -->
	<action path="/xiugairepliys" type="com.itany.bbs.action.ReplyAction" parameter="modify">
		<forward name="success" path="/adpages/showallht.jsp" redirect="false"></forward>
		<forward name="fail" path="/pages/404.html"></forward>
	</action>
	<!-- 后台删除发布帖子信息 -->
	<action path="/deletereplys" type="com.itany.bbs.action.ReplyAction" parameter="delete">
		<forward name="success" path="/adpages/showallht.jsp" redirect="false"></forward>
		<forward name="fail" path="/pages/404.html"></forward>
	</action>
	
	<!-- 获取所有用户-->
	<action path="/findallusers" type="com.itany.bbs.action.UserAction" parameter="findAllusers">
		<forward name="success" path="/adpages/alluser.jsp" redirect="false"></forward>
		<forward name="fail" path="/pages/404.html"></forward>
	</action>
	
	
	
	
	
</action-mappings>
